/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-bright": "#fdf8f8",
        "on-primary-container": "#858383",
        "surface": "#fdf8f8",
        "on-tertiary-fixed-variant": "#484645",
        "on-error": "#ffffff",
        "on-tertiary-container": "#868382",
        "on-primary": "#ffffff",
        "surface-container-high": "#ebe7e6",
        "tertiary-container": "#1c1b1a",
        "inverse-surface": "#313030",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#1c1b1a",
        "secondary-fixed": "#ffdea5",
        "on-surface": "#1c1b1b",
        "surface-tint": "#5f5e5e",
        "on-primary-fixed-variant": "#474746",
        "surface-container-highest": "#e5e2e1",
        "secondary-container": "#fed488",
        "surface-variant": "#e5e2e1",
        "on-secondary-container": "#785a1a",
        "inverse-primary": "#c8c6c5",
        "secondary": "#775a19",
        "on-secondary-fixed-variant": "#5d4201",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary-fixed": "#261900",
        "outline-variant": "#c4c7c7",
        "on-background": "#1c1b1b",
        "primary": "#000000",
        "tertiary-fixed-dim": "#cac6c4",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444748",
        "surface-container-low": "#f7f3f2",
        "surface-dim": "#ddd9d8",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c8c6c5",
        "error": "#ba1a1a",
        "outline": "#747878",
        "inverse-on-surface": "#f4f0ef",
        "secondary-fixed-dim": "#e9c176",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e6e2df",
        "surface-container": "#f1edec",
        "tertiary": "#000000",
        "background": "#fdf8f8",
        "primary-container": "#1c1b1b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "80px",
        "gutter": "24px",
        "xs": "4px",
        "base": "8px",
        "container-max": "1280px",
        "md": "24px",
        "lg": "48px",
        "sm": "12px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "button": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "button": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
